### ISSUE TITLE
Request license clarification for this module

### ISSUE THREAD

**Issue by cccscdev** [whereismyjetpack/ansible_vcenter_module#2]
I have been evaluating this module as part of a wider solution that is under development within my company.  We are interested in this module since it provides comprehensive capabilities around provisioning and customisation.

However, the lack of any license statement for this module is an issue for us.  Would it be possible to include a license file and statement within the repository?  For example, this may be something like the MIT or GPL license, etc.

We have enhanced this module to provide some additional capabilities.  We would be keen to share these back to the project, if a license statement could be made.

**Comment by whereismyjetpack** [comment]
apologies for the delay. I'm working on getting a lenience for this project, and would look forward to seeing any PRs for improvements. 

thanks for your patience

**Comment by alejojo** [comment]
Hi both, any update on this @whereismyjetpack ? it seems that your module is the right way to go, specially since pysphere is not maintained anymore: https://github.com/argos83/pysphere

> Since 2013 I'm NOT LONGER MAINTAINING this project.

Cheers!

**Comment by gbevan** [comment]
+1

**Comment by whereismyjetpack** [comment]
Thanks for the reminder. I'm going to be following up tomorrow. The past year has been kind of crazy, and this dropped on my priory list. 

As a side, I'm hoping ansible 2.2 will mitigate the need for this module, According to their roadmap (https://github.com/ansible/ansible/blob/devel/docsite/rst/roadmap/ROADMAP_2_2.rst) they would like to bring their vmware modules up to feature parity with this module, and the visat module. I'll update this issue as I get more information. Thanks for your patience, this is all new to me.
